// Plays the three pre-rendered SFX (generated by scripts/generate-sounds.mjs to match the web
// app's Web Audio synthesis). Players are created once at the app root and shared via context so
// they survive screen changes; seekTo(0) before play lets rapid answers re-trigger cleanly.

import { setAudioModeAsync, useAudioPlayer, type AudioPlayer } from 'expo-audio';
import React, { createContext, useCallback, useContext, useEffect, useMemo } from 'react';

const correctSrc = require('../../assets/sounds/correct.wav');
const wrongSrc = require('../../assets/sounds/wrong.wav');
const hardSrc = require('../../assets/sounds/hard.wav');

interface SoundContextValue {
  playCorrect: () => void;
  playWrong: () => void;
  playHard: () => void;
}

const SoundContext = createContext<SoundContextValue | null>(null);

function trigger(player: AudioPlayer) {
  try {
    // restart from the beginning, then play (so repeated taps replay the full clip)
    void player.seekTo(0);
    player.play();
  } catch {
    // audio is best-effort; never let a sound error break gameplay
  }
}

export function SoundProvider({ children }: { children: React.ReactNode }) {
  const correct = useAudioPlayer(correctSrc);
  const wrong = useAudioPlayer(wrongSrc);
  const hard = useAudioPlayer(hardSrc);

  useEffect(() => {
    // Play SFX even when the device is on silent (kids app).
    setAudioModeAsync({ playsInSilentMode: true }).catch(() => {});
  }, []);

  const playCorrect = useCallback(() => trigger(correct), [correct]);
  const playWrong = useCallback(() => trigger(wrong), [wrong]);
  const playHard = useCallback(() => trigger(hard), [hard]);

  const value = useMemo<SoundContextValue>(
    () => ({ playCorrect, playWrong, playHard }),
    [playCorrect, playWrong, playHard]
  );

  return <SoundContext.Provider value={value}>{children}</SoundContext.Provider>;
}

export function useSound(): SoundContextValue {
  const ctx = useContext(SoundContext);
  if (!ctx) throw new Error('useSound must be used within SoundProvider');
  return ctx;
}
